### PR TITLE
Don't process 'normalize' and 'max_pts' cols as assignments

### PR DESCRIPTION
**Pull request by pwilkins**
Pylmod has an array of column names that will not be considered as assignment names.  Column names that are not in this array are processed as assignment scores.  This change adds the contents of the ``max_points_column`` and ``normalize_column`` parameters to this array.

@pdpinch @bdero

### CODE REVIEW

**Comment by noisecapella** [comment]
This should be a PR against the other PR, as it is it will merge to master instead. Also, can we add a test to cover this bug? Here's my suggestion, towards the bottom of test_gradebook.py:

    @mock.patch('csv.DictReader')
    def test_spreadsheet2gradebook_max_points(self, csv_patch, multi_patch):
        """
        Make sure that the new arguments added are passed to
        _spreadsheet2gradebook_multi
        """
        gradebook = GradeBook(self.CERT, self.URLBASE)

        with tempfile.NamedTemporaryFile(delete=True) as temp_file:
            gradebook.spreadsheet2gradebook(
                temp_file.name,
                use_max_points_column=True,
                max_points_column='max_pts',
                normalize_column='normalize'
            )
            args, kwargs = multi_patch.call_args
            assert csv_patch.call_count == 1
            self.assertEqual(kwargs['use_max_points_column'], True)
            self.assertEqual(kwargs['max_points_column'], 'max_pts')
            self.assertEqual(kwargs['normalize_column'], 'normalize')
            self.assertEqual(args[2], ['External email', 'max_pts', 'normalize'])

**Comment by pwilkins** [comment]
@noisecapella Am I correct that this is testing whether the contents of the ``max_points_column`` and ``normalize_column`` are passed to ``spreadsheet2gradebook()``?  If so, that doesn't test my code change.
My code appends the contents of those parameters to the ``non_assignment_fields`` array.

**Comment by noisecapella** [comment]
The last line should test the `non_assignment_fields` array, which is passed as a positional argument

**Comment by pwilkins** [comment]
I'm going to close this PR and reopen it against #61 as @noisecapella recommended.

**Comment by pwilkins** [comment]
This PR is replaced by PR #66

**Pull request closed without merging**
