### PR TITLE
Upgrade to Python 3

### PR DESCRIPTION
**Pull request by markbreedlove**
This changeset updates `PyLmod` to run on Python 3.7.

See the commit message in commit https://github.com/mitodl/PyLmod/commit/3de7b84390eac7813d149914ffc37e5716a8f486

It's necessary to upgrade and release a new version of `PyLmod` in order to upgrade `lmod_proxy`. 

#### What are the relevant tickets?

https://github.com/mitodl/lmod_proxy/issues/62

### CODE REVIEW

**Comment by markbreedlove** [comment]
I will try to perform a test of this and `lmod_proxy` with a local installation before merging it. I'm working on that now, setting up my certificate, etc.

**Comment by markbreedlove** [comment]
Also TODO: Upon merge and release we'll want to push the package to PyPI.

**Comment by markbreedlove** [comment]
Please hold -- I think I may have discovered a problem when running the app locally.

**Comment by markbreedlove** [comment]
All's well -- OK to resume reviewing.

**Comment by blarghmatey** [comment]
:+1:

**Pull request merged**
